const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');const {PGlite}=require('@electric-sql/pglite');const {createCouponService}=require('../services/couponService');const {createPromotionPricingService}=require('../services/promotionPricingService');const {createCouponCheckoutService}=require('../services/couponCheckoutService');const {createOrderCodeService}=require('../services/orderCodeService');const {orderGetType}=require('../services/orderManagementService');
async function fixture(){const db=new PGlite();await db.exec(fs.readFileSync('database/schema.postgres.sql','utf8'));for(const f of ['20260907_order_codes','20260907_unbound_order_codes','20260909_order_fulfillment','20260910_manual_codes','20260910_coupons'])await db.exec(fs.readFileSync('database/migrations/'+f+'.sql','utf8'));await db.exec("ALTER TABLE order_items ADD COLUMN size TEXT;ALTER TABLE orders ADD COLUMN bound_device_id TEXT;ALTER TABLE orders ADD COLUMN manufacturer_sync_status TEXT;ALTER TABLE orders ADD COLUMN manufacturer_sync_error TEXT;ALTER TABLE orders ADD COLUMN manufacturer_response TEXT;INSERT INTO users(user_id,username) VALUES('u','Quanshan'),('other','Other');INSERT INTO products(product_id,product_name,unit_price,pickup_method) VALUES('a','A',100,'pickup'),('b','B',50,'shipping'),('gift','Gift',30,'pickup');INSERT INTO templates(template_id,template_name) VALUES('t','Template');INSERT INTO events(event_id,event_name,event_type,status) VALUES(1,'20 off A','promotion_discount','active');INSERT INTO promotion_discount_events(event_id,promo_scope,target_product_ids,discount_type,discount_value) VALUES(1,'selected_products','[\"a\"]','percent_off',20);");const pool={query:(...x)=>db.query(...x),connect:async()=>({query:(...x)=>db.query(...x),release(){}})};const pricing=createPromotionPricingService(pool),coupons=createCouponService(pool,pricing);return {db,pool,pricing,coupons};}
const base={coupon_name:'Coupon',deal_type:'money_off',coupon_available_items:['a'],condition_amount:0,reduce_amount:10,status:'published',coupon_scene_type:['商城']};
test('coupon schema, grants, identity, dates, targeted reductions, gift products and hidden coupon ids',async()=>{const {db,coupons}=await fixture();try{
 await assert.rejects(coupons.save(null,{...base,coupon_available_items:[]}),/至少/);await assert.rejects(coupons.save(null,{...base,coupon_available_items:['missing']}),/不存在/);
 const c=await coupons.save(null,base);await coupons.grant(c.id,['u']);await coupons.grant(c.id,['u']);const wallet=await coupons.wallet('u');assert.equal(wallet.coupons.length,1);assert.equal(wallet.coupons[0].coupon_id,undefined);const id=wallet.coupons[0].selection_id;
 const quote=await coupons.quote([{id:'a',qty:1,price:1},{id:'b',qty:1}], 'u',id);assert.equal(quote.total,120);assert.equal(quote.activityDiscount,20);assert.equal(quote.couponDiscount,10);assert.equal(quote.items[1].lineTotal,50);
 await assert.rejects(coupons.quote([{id:'a'}],'other',id),/不可用/);await assert.rejects(coupons.quote([{id:'b'}],'u',id),/条件/);
 await coupons.save(c.id,{...base,deal_type:'percent_off',discount:25});assert.equal((await coupons.quote([{id:'a'}],'u',id)).total,60);
 await coupons.save(c.id,{...base,start_date:'2099-01-01',expiry_date:'2100-01-01'});assert.equal((await coupons.wallet('u')).coupons[0].coupon_use_status,'inactive');
 await coupons.save(c.id,{...base,start_date:'2000-01-01',expiry_date:'2001-01-01'});assert.equal((await coupons.wallet('u')).coupons[0].coupon_use_status,'expired');
 await coupons.save(c.id,{...base,start_date:null,expiry_date:null,deal_type:'free_product',rewarded_items:[{type:'product',id:'gift'},{type:'template',id:'t'}]});const gifts=await coupons.quote([{id:'a'}],'u',id);assert.equal(gifts.total,80);assert.equal(gifts.items[1].price,0);assert.equal(gifts.items[1].lineTotal,0);assert.deepEqual(gifts.rewardTemplates,['t']);
 const link=await coupons.claimLink(c.id);await coupons.claim(link.url.split('=')[1],'other');assert.equal((await coupons.wallet('other')).coupons.length,1);
 }finally{await db.close();}});
test('durable reservation, unknown payment retry, paid order atomic redemption and template collection',async()=>{const {db,pool,coupons}=await fixture();try{
 const c=await coupons.save(null,{...base,deal_type:'free_product',rewarded_items:[{type:'product',id:'gift'},{type:'template',id:'t'}]});await coupons.grant(c.id,['u']);const id=(await coupons.wallet('u')).coupons[0].selection_id,items=[{id:'a',qty:1}],quote=await coupons.quote(items,'u',id);
 const source=fs.readFileSync('server.js','utf8'),a=source.indexOf('async function createPaidOrderRecord('),b=source.indexOf('\nasync function ',a+1);const ctx={crypto,orderGetType,hasPostgresRuntime:()=>true,ensurePgAdminRuntimeSchema:async()=>{},pgPool:pool,orderCodes:createOrderCodeService(pool),couponService:coupons,cleanPgText:x=>String(x||''),pgNumber:x=>Number(x||0),resolveOrderUserId:async()=> 'u',ensurePrintServiceProduct:async()=>null,notifyManufacturerOrder:async()=>({status:'not_configured',error:'',response:''})};vm.createContext(ctx);vm.runInContext(source.slice(a,b)+';this.create=createPaidOrderRecord',ctx);
 const calls=[];const payment={browserConfig:()=>({currency:'AUD'}),createPayment:async request=>{calls.push(request);return calls.length===1?{httpStatus:502,body:{ok:false,error:'Unknown network result'}}:{httpStatus:200,body:{ok:true,status:'COMPLETED',paymentId:'pay-1',amount:80}};}};
 const service=createCouponCheckoutService({pool,coupons,payment,createOrder:ctx.create,getSession:async()=>({ok:true,user:{userId:'u'}})});
 const body={items,sessionId:'s',couponSelection:id,pricingKey:quote.pricingKey,amount:quote.total,sourceId:'first-token',idempotencyKey:'checkout_test1'};
 const uncertain=await service.pay(body);assert.equal(uncertain.body.retrySameAttempt,true);let grant=(await db.query('SELECT * FROM user_coupons WHERE user_coupon_id=$1',[id])).rows[0];assert(grant.order_id);assert.equal(grant.coupon_use_status,'unused');
 await assert.rejects(service.pay({...body,idempotencyKey:'checkout_other'}),/待完成/);
 const paid=await service.pay({...body,sourceId:'new-token'});assert.equal(paid.body.ok,true);assert.equal(paid.body.order.ok,true);assert.equal(calls[1].sourceId,'first-token');assert.equal(calls[1].idempotencyKey,calls[0].idempotencyKey);
 grant=(await db.query('SELECT * FROM user_coupons WHERE user_coupon_id=$1',[id])).rows[0];assert.equal(grant.coupon_use_status,'used');assert.equal(grant.order_id,paid.body.order.orderId);
 assert.equal((await db.query("SELECT unit_price FROM order_items WHERE product_id='gift'")).rows[0].unit_price,0);assert.equal((await db.query("SELECT count(*)::int n FROM gallery_templates WHERE gallery_type='personal' AND template_id='t' AND user_id='u'")).rows[0].n,1);
 const again=await service.pay(body);assert.equal(again.body.order.orderId,paid.body.order.orderId);assert.equal(calls.length,2);assert.equal((await db.query('SELECT count(*)::int n FROM orders')).rows[0].n,1);
 await db.query("UPDATE coupons SET expiry_date='2001-01-01' WHERE coupon_id=$1",[c.id]);assert.equal((await coupons.wallet('u')).coupons[0].coupon_use_status,'used');
 }finally{await db.close();}});

test('zero-total coupon checkout bypasses charging and definitive failure releases the coupon',async()=>{const {db,pool,coupons}=await fixture();try{
 const coupon=await coupons.save(null,{...base,reduce_amount:100});await coupons.grant(coupon.id,['u']);const id=(await coupons.wallet('u')).coupons[0].selection_id;const items=[{id:'a'}];let quote=await coupons.quote(items,'u',id);let calls=0;
 const payment={browserConfig:()=>({currency:'AUD'}),createPayment:async()=>{calls++;return {httpStatus:402,body:{ok:false,error:'Declined'}};}};
 const service=createCouponCheckoutService({pool,coupons,payment,getSession:async()=>({ok:true,user:{userId:'u'}}),createOrder:async body=>{await coupons.transaction(c=>coupons.redeem(c,body.couponSelection,'u',body.reservedOrderId,[]));return {ok:true,orderId:body.reservedOrderId};}});
 const result=await service.pay({items,couponSelection:id,pricingKey:quote.pricingKey,amount:0,idempotencyKey:'checkout_zero',sessionId:'private-session'});assert.equal(result.body.ok,true);assert.equal(calls,0);assert.equal((await coupons.wallet('u')).coupons[0].coupon_use_status,'used');assert.equal((await db.query("SELECT payment_request FROM coupon_checkouts WHERE checkout_id='checkout_zero'")).rows[0].payment_request.sessionId,undefined);
 const second=await coupons.save(null,base);await coupons.grant(second.id,['u']);const sid=(await coupons.wallet('u')).coupons.find(c=>c.coupon_use_status==='unused').selection_id;quote=await coupons.quote(items,'u',sid);
 const declined=await service.pay({items,couponSelection:sid,pricingKey:quote.pricingKey,amount:quote.total,idempotencyKey:'checkout_decline',sourceId:'token'});assert.equal(declined.body.retrySameAttempt,false);const row=(await db.query('SELECT * FROM user_coupons WHERE user_coupon_id=$1',[sid])).rows[0];assert.equal(row.order_id,null);assert.equal(row.checkout_id,null);assert.equal(row.coupon_use_status,'unused');assert.equal(calls,1);
 }finally{await db.close();}});

test('shop shows published shop coupons and external activities; product lookup checks exact database identities',async()=>{const {db,coupons}=await fixture();try{
 await coupons.save(null,{...base,coupon_name:'Shop'});await coupons.save(null,{...base,coupon_name:'Hidden',status:'unpublished'});await coupons.save(null,{...base,coupon_name:'Task',coupon_scene_type:['任务奖励']});
 await db.query("INSERT INTO events(event_id,event_name,event_title,event_type,status) VALUES(2,'social','Social Title','external_social','active'),(3,'hidden','Hidden Title','external_social','inactive')");
 const shop=await coupons.storefront();assert.deepEqual(shop.coupons.map(c=>c.coupon_name),['Shop']);assert.equal(shop.coupons[0].coupon_id,undefined);assert.deepEqual(shop.activities.map(a=>a.title),['Social Title']);
 assert.equal((await coupons.findProducts('a')).products[0].value,'a');assert.equal((await coupons.findProducts('A')).products[0].value,'a');assert.equal((await coupons.findProducts('missing')).products.length,0);await assert.rejects(coupons.findProducts(''),/请输入/);
 }finally{await db.close();}});
