const crypto=require('node:crypto');
const TYPES=['money_off','percent_off','buy_x_get_y','free_product'];
const SCENES=['商城','积分兑换','任务奖励','第三方平台'];
const money=v=>{const n=Number(v||0);if(!Number.isFinite(n)||n<0||n>1e9)throw Error('金额无效');return Math.round(n*100)/100;};
const array=v=>{if(Array.isArray(v))return v;try{const a=JSON.parse(v);if(Array.isArray(a))return a;}catch{}return String(v||'').split(/[,，\s]+/).filter(Boolean);};
const unique=v=>[...new Set(array(v).map(String))];
function createCouponService(pool,pricing){
 async function transaction(fn){const c=await pool.connect();try{await c.query('BEGIN');const r=await fn(c);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 async function refresh(c=pool){await c.query(`UPDATE user_coupons u SET coupon_use_status=CASE WHEN c.expiry_date IS NOT NULL AND c.expiry_date<>'' AND c.expiry_date::timestamptz<=now() THEN 'expired' WHEN c.start_date>now() THEN 'inactive' ELSE 'unused' END FROM coupons c WHERE c.coupon_id=u.coupon_id AND u.coupon_use_status<>'used' AND u.coupon_use_status IS DISTINCT FROM CASE WHEN c.expiry_date IS NOT NULL AND c.expiry_date<>'' AND c.expiry_date::timestamptz<=now() THEN 'expired' WHEN c.start_date>now() THEN 'inactive' ELSE 'unused' END`);}
 async function options(){const [products,templates,users]=await Promise.all([pool.query("SELECT product_id AS value,product_name AS label FROM products WHERE status='active' ORDER BY product_name"),pool.query("SELECT template_id AS value,template_name AS label FROM templates WHERE status='active' ORDER BY template_name"),pool.query('SELECT user_id AS value,username AS label FROM users ORDER BY username')]);return {products:products.rows,templates:templates.rows,users:users.rows};}
 async function adminList(){await refresh();return {ok:true,rows:(await pool.query('SELECT * FROM coupons ORDER BY created_at DESC')).rows,assignments:(await pool.query('SELECT u.*,p.username FROM user_coupons u JOIN users p ON p.user_id=u.user_id ORDER BY u.created_at DESC')).rows,options:await options()};}
 async function save(id,input){return transaction(async c=>{
 const old=id?(await c.query('SELECT * FROM coupons WHERE coupon_id=$1 FOR UPDATE',[id])).rows[0]:null;if(id&&!old)throw Error('优惠券不存在');const v={...old,...input};
 const items=unique(v.coupon_available_items),scenes=unique(v.coupon_scene_type||['商城']);if(!items.length)throw Error('至少选择一个适用商品');if(!scenes.length||scenes.some(x=>!SCENES.includes(x)))throw Error('请选择有效使用场景');
 if(!String(v.coupon_name||'').trim()||!TYPES.includes(v.deal_type)||!['published','unpublished'].includes(v.status))throw Error('优惠券名称、类型或上架状态无效');
 const found=(await c.query('SELECT product_id FROM products WHERE product_id=ANY($1::text[])',[items])).rows;if(found.length!==items.length)throw Error('适用商品编号不存在');
 const start=v.start_date?new Date(v.start_date):null,end=v.expiry_date?new Date(v.expiry_date):null;if((start&&isNaN(start))||(end&&isNaN(end))||(start&&end&&start>=end))throw Error('有效期无效');
 const discount=money(v.discount);if(discount>100)throw Error('减免百分比不能超过100');
 let rewards=[];if(['free_product','buy_x_get_y'].includes(v.deal_type)){
 const raw=array(v.rewarded_items);if(!raw.length)throw Error('请选择赠送商品或模板');
 for(const item of raw){if(!item||!['product','template'].includes(item.type)||typeof item.id!=='string')throw Error('赠品格式无效');const table=item.type==='product'?'products':'templates',key=item.type==='product'?'product_id':'template_id';if(!(await c.query(`SELECT 1 FROM ${table} WHERE ${key}=$1 AND status='active'`,[item.id])).rows.length)throw Error('赠品不存在或已停用');if(!rewards.some(r=>r.type===item.type&&r.id===item.id))rewards.push({type:item.type,id:item.id});}
 }
 if(v.coupon_url&&!/^https?:\/\//.test(v.coupon_url)&&!/^\/coupon-wallet\.html\?claim=/.test(v.coupon_url))throw Error('领取链接必须是HTTP(S)网址');
 const couponId=id||'coupon_'+crypto.randomUUID();
 await c.query(`INSERT INTO coupons(coupon_id,coupon_name,coupon_type,deal_type,coupon_available_items,condition_amount,reduce_amount,discount,rewarded_items,start_date,expiry_date,status,coupon_scene_type,coupon_url) VALUES($1,$2,$3,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT(coupon_id) DO UPDATE SET coupon_name=EXCLUDED.coupon_name,coupon_type=EXCLUDED.coupon_type,deal_type=EXCLUDED.deal_type,coupon_available_items=EXCLUDED.coupon_available_items,condition_amount=EXCLUDED.condition_amount,reduce_amount=EXCLUDED.reduce_amount,discount=EXCLUDED.discount,rewarded_items=EXCLUDED.rewarded_items,start_date=EXCLUDED.start_date,expiry_date=EXCLUDED.expiry_date,status=EXCLUDED.status,coupon_scene_type=EXCLUDED.coupon_scene_type,coupon_url=EXCLUDED.coupon_url,updated_at=now()`,[couponId,v.coupon_name.trim(),v.deal_type,JSON.stringify(items),money(v.condition_amount),v.deal_type==='money_off'?money(v.reduce_amount):0,v.deal_type==='percent_off'?discount:0,JSON.stringify(rewards),start?.toISOString()||null,end?.toISOString()||null,v.status,JSON.stringify(scenes),v.coupon_url||null]);return {ok:true,id:couponId};
 });}
 async function grant(couponId,userIds){return transaction(async c=>{if(!(await c.query('SELECT 1 FROM coupons WHERE coupon_id=$1',[couponId])).rows.length)throw Error('优惠券不存在');for(const user of unique(userIds)){await c.query("INSERT INTO user_coupons(user_coupon_id,coupon_id,user_id,coupon_use_status) VALUES($1,$2,$3,'inactive') ON CONFLICT(coupon_id,user_id) DO NOTHING",['uc_'+crypto.randomUUID(),couponId,user]);}await refresh(c);return {ok:true};});}
 async function claimLink(id){const token=crypto.randomBytes(24).toString('hex'),url='/coupon-wallet.html?claim='+token;const r=await pool.query('UPDATE coupons SET claim_token=$1,coupon_url=$2 WHERE coupon_id=$3 RETURNING coupon_id',[token,url,id]);if(!r.rows.length)throw Error('优惠券不存在');return {ok:true,url};}
 async function claim(token,userId){const row=(await pool.query("SELECT coupon_id FROM coupons WHERE claim_token=$1 AND status='published' AND (expiry_date IS NULL OR expiry_date::timestamptz>now())",[token])).rows[0];if(!row)throw Error('领取链接无效或优惠券已过期');return grant(row.coupon_id,[userId]);}
 async function wallet(userId){await refresh();const rows=(await pool.query(`SELECT u.user_coupon_id AS selection_id,u.coupon_use_status,u.order_id,u.checkout_id,c.coupon_name,c.deal_type,c.coupon_available_items,c.condition_amount,c.reduce_amount,c.discount,c.rewarded_items,c.start_date,c.expiry_date,c.status,c.coupon_scene_type FROM user_coupons u JOIN coupons c ON c.coupon_id=u.coupon_id WHERE u.user_id=$1 ORDER BY u.created_at DESC`,[userId])).rows;const templates=(await pool.query(`SELECT DISTINCT t.template_id,t.template_name,t.design_type,t.nail_shape,t.tags,a.url AS image_url,a.mime_type,a.base64_data FROM gallery_templates g JOIN personal_galleries pg ON pg.personal_gallery_id=g.gallery_id JOIN templates t ON t.template_id=g.template_id LEFT JOIN assets a ON a.asset_id=COALESCE(t.cover_asset_id,t.image_asset_id) WHERE g.gallery_type='personal' AND pg.user_id=$1 AND g.user_id=$1`,[userId])).rows.map(t=>({...t,image_url:t.image_url||(t.base64_data?(t.base64_data.startsWith('data:')?t.base64_data:`data:${t.mime_type||'image/png'};base64,${t.base64_data}`):''),base64_data:undefined}));return {ok:true,coupons:rows,templates};}
 async function quote(items,userId,selectionId){const base=await pricing.quote(items.filter(i=>!i.couponGift));if(!selectionId)return base;if(!userId)throw Error('请先登录再使用优惠券');await refresh();
 const row=(await pool.query('SELECT c.*,u.user_coupon_id,u.coupon_use_status,u.checkout_id FROM user_coupons u JOIN coupons c ON c.coupon_id=u.coupon_id WHERE u.user_coupon_id=$1 AND u.user_id=$2',[selectionId,userId])).rows[0];
 if(!row||row.status!=='published'||row.coupon_use_status!=='unused'||!array(row.coupon_scene_type).includes('商城'))throw Error('优惠券不可用、未生效或已过期');
 const eligible=base.items.filter(i=>array(row.coupon_available_items).includes(String(i.id))),subtotal=eligible.reduce((s,i)=>s+Math.round(i.lineTotal*100),0);
 if(!eligible.length||subtotal<Math.round(Number(row.condition_amount)*100))throw Error('未满足优惠券适用商品或金额条件');
 const reduction=row.deal_type==='money_off'?Math.round(Number(row.reduce_amount)*100):row.deal_type==='percent_off'?Math.round(subtotal*Number(row.discount)/100):0;
 const off=Math.min(subtotal,reduction);let allocated=0,cumulative=0;
 for(const item of eligible){cumulative+=Math.round(item.lineTotal*100);const share=Math.round(off*cumulative/subtotal||0)-allocated;allocated+=share;item.lineTotal=(Math.round(item.lineTotal*100)-share)/100;item.lineDiscount=Math.round((item.lineDiscount+share/100)*100)/100;}
 const rewards=array(row.rewarded_items);for(const gift of rewards.filter(r=>r.type==='product')){const product=(await pool.query("SELECT product_id,product_name,image_url,pickup_method FROM products WHERE product_id=$1 AND status='active'",[gift.id])).rows[0];if(!product)throw Error('赠品已不可用');base.items.push({id:product.product_id,name:product.product_name,qty:1,price:0,lineTotal:0,lineDiscount:0,image:product.image_url,couponGift:true,pickup_method:product.pickup_method});}
 if(base.items.length>50)throw Error('购物车含赠品最多50项');
 base.activityDiscount=base.discount;base.couponDiscount=off/100;base.discount=Math.round((base.discount+off/100)*100)/100;base.total=Math.round((base.total-off/100)*100)/100;
 base.coupon={selectionId,name:row.coupon_name};base.couponRevision=new Date(row.updated_at).toISOString();base.rewardTemplates=rewards.filter(r=>r.type==='template').map(r=>r.id);base.pricingKey=crypto.createHash('sha256').update(JSON.stringify({base:base.pricingKey,selectionId,updated:row.updated_at,total:base.total,gifts:rewards})).digest('hex');return base;
 }
 async function redeem(client,selectionId,userId,orderId,templateIds=[]){
 const row=(await client.query('SELECT * FROM user_coupons WHERE user_coupon_id=$1 AND user_id=$2 FOR UPDATE',[selectionId,userId])).rows[0];if(!row||row.order_id!==orderId)throw Error('优惠券订单绑定不一致');if(row.coupon_use_status==='used'){if(row.order_id===orderId)return;throw Error('优惠券已使用');}
 await client.query("UPDATE user_coupons SET coupon_use_status='used',used_at=now() WHERE user_coupon_id=$1",[selectionId]);
 for(const id of templateIds){let gallery=(await client.query('SELECT personal_gallery_id FROM personal_galleries WHERE user_id=$1 ORDER BY created_at LIMIT 1',[userId])).rows[0]?.personal_gallery_id;
 if(!gallery){gallery='pg_'+crypto.randomUUID();await client.query("INSERT INTO personal_galleries(personal_gallery_id,user_id,gallery_name) VALUES($1,$2,'优惠券收藏')",[gallery,userId]);}
 await client.query("INSERT INTO gallery_templates(gallery_template_id,gallery_type,gallery_id,template_id,user_id) VALUES($1,'personal',$2,$3,$4) ON CONFLICT(gallery_type,gallery_id,template_id) DO NOTHING",['gt_'+crypto.randomUUID(),gallery,id,userId]);}
 }
 return {adminList,save,grant,claimLink,claim,wallet,quote,refresh,redeem,transaction};
}
module.exports={createCouponService};
