const crypto=require('node:crypto');const {createTemplateRepository,FIELDS,source}=require('../database/templateRepository');
function imageIds(row){try{const v=JSON.parse(row?.image_asset_ids||'[]');return [...new Set([row?.cover_asset_id,row?.image_asset_id,...(Array.isArray(v)?v:[])].filter(Boolean))];}catch{return [row?.cover_asset_id||row?.image_asset_id].filter(Boolean);}}
function createTemplateAdminService(pool){const repo=createTemplateRepository(pool);
 async function detail(type,id){source(type);const row=id?await repo.get(repo,type,id):null;if(id&&!row)throw new Error('Template not found in this library');const galleries=await repo.galleries(repo,type);if(!row)return {ok:true,record:null,galleries};
 const links=(await repo.query('SELECT gallery_id FROM gallery_templates WHERE template_id=$1 AND gallery_type=$2',[id,type])).rows;
 const assets=await repo.assets(repo,imageIds(row));return {ok:true,record:{...row,gallery_ids:links.map(x=>x.gallery_id),images:imageIds(row).map(id=>assets.find(a=>a.asset_id===id)).filter(Boolean).map(a=>({asset_id:a.asset_id,url:a.url|| (a.base64_data?`data:${a.mime_type||'image/png'};base64,${a.base64_data}`:'')}))},galleries};}
 async function save(type,id,input){source(type);return repo.transaction(async c=>{const old=id?await repo.get(c,type,id,true):null;if(id&&!old)throw new Error('Template not found in this library');const values={};for(const key of FIELDS){if(Object.hasOwn(input,key)){if(input[key]!==null&&typeof input[key]!=='string')throw new Error(`Invalid ${key}`);values[key]=input[key]?.trim()||null;}}
 const merged={...old,...values};if(!merged.template_name)throw new Error('Template name is required');
 for(const [key,allowed,fallback] of [['visibility',['public','private'],'public'],['status',['active','inactive'],'active']]){if(!old&&!values[key])values[key]=fallback;if(!allowed.includes(Object.hasOwn(values,key)?values[key]:(old?.[key]??fallback)))throw new Error(`Invalid ${key}`);}
 if(!old){values.template_type=values.template_type||'nail';values.design_type=values.design_type||'nail';values.template_title=values.template_title||values.template_name;}
 for(const key of ['template_type','design_type']){if(Object.hasOwn(values,key)&&!values[key])throw new Error(`${key} is required`);}
 if(values.template_object_json){try{JSON.parse(values.template_object_json);}catch{throw new Error('Template object must be valid JSON');}}
 if(values.event_id&&!/^\d+$/.test(values.event_id))throw new Error('Event ID must be numeric');
 if(values.published_at){if(Number.isNaN(Date.parse(values.published_at)))throw new Error('Invalid publish date');values.published_at=new Date(values.published_at).toISOString();}
 for(const [key,table,idKey] of [['author_user_id','users','user_id'],['author_avatar_asset_id','assets','asset_id'],['event_id','events','event_id']]){if(values[key]&&!(await c.query(`SELECT 1 FROM ${table} WHERE ${idKey}=$1`,[values[key]])).rows.length)throw new Error(`${key} does not exist`);}
 let kept=Object.hasOwn(input,'image_asset_ids')?input.image_asset_ids:imageIds(old);if(!Array.isArray(kept)||!kept.every(x=>typeof x==='string'))throw new Error('Invalid image IDs');kept=[...new Set(kept)];if((await repo.assets(c,kept)).length!==kept.length)throw new Error('Image asset does not exist');
 const uploads=input.images||[];if(!Array.isArray(uploads)||kept.length+uploads.length>6)throw new Error('Use one to six images');if(!kept.length&&!uploads.length)throw new Error('At least one image is required');
 for(const item of uploads){if(typeof item!=='string')throw new Error('Invalid image');if(/^https?:\/\//i.test(item)){const url=new URL(item);if(!['http:','https:'].includes(url.protocol))throw new Error('Invalid image URL');kept.push(await repo.image(c,merged.author_user_id,{url:item}));}else{const m=item.match(/^data:(image\/(?:png|jpeg|webp));base64,([A-Za-z0-9+/=\s]+)$/);if(!m||Buffer.from(m[2],'base64').length>8*1024*1024)throw new Error('Use PNG/JPEG/WEBP images up to 8 MB');kept.push(await repo.image(c,merged.author_user_id,{mime:m[1],base64:m[2]}));}}
 const cover=input.cover_asset_id||kept[0];if(!kept.includes(cover))throw new Error('Cover must be one of the retained images');values.cover_asset_id=cover;values.image_asset_id=cover;values.image_asset_ids=JSON.stringify(kept);
 let galleries;if(Object.hasOwn(input,'gallery_ids')){galleries=input.gallery_ids;if(!Array.isArray(galleries))throw new Error('Invalid galleries');const valid=await repo.galleries(c,type);if(!galleries.every(x=>valid.some(g=>g.id===x)))throw new Error('Gallery does not belong to this library');galleries=[...new Set(galleries)];}
 const templateId=id||`${type}_${crypto.randomUUID()}`;const row=await repo.save(c,type,templateId,values,old);if(galleries)await repo.link(c,type,templateId,galleries,row.author_user_id);return {ok:true,templateId};});}
 return {detail,save};}
module.exports={createTemplateAdminService};
